//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public Candidate()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int CandidateId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public string ResumePath { get; set; }
        public Nullable<int> TechnologyId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ReferrerId { get; set; }
        public string ReferrerOther { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<decimal> ExpectedCTC { get; set; }
        public Nullable<decimal> CurrentCTC { get; set; }
        public Nullable<decimal> OfferedCTC { get; set; }
    
        public virtual Referrer Referrer { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
