//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Category = new HashSet<Category>();
            this.Designation = new HashSet<Designation>();
            this.Profile = new HashSet<Profile>();
            this.ActionList = new HashSet<ActionList>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> BreakThroughObjectiveYear { get; set; }
        public bool Active { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> RecordDeleted { get; set; }
    
        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<Designation> Designation { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<ActionList> ActionList { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
