//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ActionItemResponsible = new HashSet<ActionItemResponsible>();
            this.ActionItemResponsible1 = new HashSet<ActionItemResponsible>();
            this.ActionItemResponsible2 = new HashSet<ActionItemResponsible>();
            this.ActionList = new HashSet<ActionList>();
            this.ActionList1 = new HashSet<ActionList>();
            this.ActionList2 = new HashSet<ActionList>();
            this.Comments1 = new HashSet<Comments>();
            this.Comments2 = new HashSet<Comments>();
            this.Employee1 = new HashSet<Employee>();
            this.FileAttachments = new HashSet<FileAttachments>();
            this.FileAttachments1 = new HashSet<FileAttachments>();
            this.FileAttachments2 = new HashSet<FileAttachments>();
            this.Module = new HashSet<Module>();
            this.Module1 = new HashSet<Module>();
            this.Profile = new HashSet<Profile>();
            this.Profile1 = new HashSet<Profile>();
            this.ProfilePermission = new HashSet<ProfilePermission>();
            this.ProfilePermission1 = new HashSet<ProfilePermission>();
            this.Project = new HashSet<Project>();
            this.Resources = new HashSet<Resources>();
            this.TimeSheet = new HashSet<TimeSheet>();
            this.UserGroup = new HashSet<UserGroup>();
            this.ProjectGroup = new HashSet<ProjectGroup>();
            this.InterviewDetail = new HashSet<InterviewDetail>();
            this.Leaves = new HashSet<Leaves>();
            this.Leaves1 = new HashSet<Leaves>();
            this.LeavesApprovedBy = new HashSet<LeavesApprovedBy>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string CorrespondenceAddr { get; set; }
        public string PermanentAddr { get; set; }
        public string PAN { get; set; }
        public Nullable<int> ReportTo { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Password { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<int> OrgUnitId { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public bool IsRegisteredUser { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> RecordDeleted { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
        public string UserNote { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<bool> IsLinkSend { get; set; }
        public Nullable<System.DateTime> LinkSendDate { get; set; }
        public string UserGuid { get; set; }
        public Nullable<int> TechnologyId { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ReferrerId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string EmpCode { get; set; }
    
        public virtual ICollection<ActionItemResponsible> ActionItemResponsible { get; set; }
        public virtual ICollection<ActionItemResponsible> ActionItemResponsible1 { get; set; }
        public virtual ICollection<ActionItemResponsible> ActionItemResponsible2 { get; set; }
        public virtual ICollection<ActionList> ActionList { get; set; }
        public virtual ICollection<ActionList> ActionList1 { get; set; }
        public virtual ICollection<ActionList> ActionList2 { get; set; }
        public virtual Attachment Attachment { get; set; }
        public virtual Candidate Candidate { get; set; }
        public virtual ICollection<Comments> Comments1 { get; set; }
        public virtual ICollection<Comments> Comments2 { get; set; }
        public virtual Company Company { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual ICollection<FileAttachments> FileAttachments { get; set; }
        public virtual ICollection<FileAttachments> FileAttachments1 { get; set; }
        public virtual ICollection<FileAttachments> FileAttachments2 { get; set; }
        public virtual ICollection<Module> Module { get; set; }
        public virtual ICollection<Module> Module1 { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<Profile> Profile1 { get; set; }
        public virtual ICollection<ProfilePermission> ProfilePermission { get; set; }
        public virtual ICollection<ProfilePermission> ProfilePermission1 { get; set; }
        public virtual ICollection<Project> Project { get; set; }
        public virtual ICollection<Resources> Resources { get; set; }
        public virtual ICollection<TimeSheet> TimeSheet { get; set; }
        public virtual OrganizationUnit OrganizationUnit { get; set; }
        public virtual Profile Profile2 { get; set; }
        public virtual Referrer Referrer { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual ICollection<UserGroup> UserGroup { get; set; }
        public virtual ICollection<ProjectGroup> ProjectGroup { get; set; }
        public virtual ICollection<InterviewDetail> InterviewDetail { get; set; }
        public virtual ICollection<Leaves> Leaves { get; set; }
        public virtual ICollection<Leaves> Leaves1 { get; set; }
        public virtual ICollection<LeavesApprovedBy> LeavesApprovedBy { get; set; }
    }
}
