//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewDetailSkill
    {
        public int InterviewDetailSkillId { get; set; }
        public Nullable<int> InterviewDetailId { get; set; }
        public Nullable<int> SkillId { get; set; }
    
        public virtual InterviewDetail InterviewDetail { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
