//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaves
    {
        public Leaves()
        {
            this.LeavesApprovedBy = new HashSet<LeavesApprovedBy>();
        }
    
        public int LeaveId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Reason { get; set; }
        public Nullable<bool> ApprovedStatus { get; set; }
        public Nullable<int> ApprovedById { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual ICollection<LeavesApprovedBy> LeavesApprovedBy { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
