//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.Leaves = new HashSet<Leaves>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Leaves> Leaves { get; set; }
    }
}
