//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulePermission
    {
        public ModulePermission()
        {
            this.ProfilePermission = new HashSet<ProfilePermission>();
        }
    
        public int ModulePermissionId { get; set; }
        public int ModuleId { get; set; }
        public int PermissionId { get; set; }
        public bool IsReadOnly { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual ICollection<ProfilePermission> ProfilePermission { get; set; }
    }
}
