//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUnit
    {
        public OrganizationUnit()
        {
            this.OrganizationUnit1 = new HashSet<OrganizationUnit>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int OrgUnitId { get; set; }
        public string OrgUnitName { get; set; }
        public Nullable<int> ParentOrgUnitId { get; set; }
        public bool IsDefaultUnit { get; set; }
        public bool IsDefaultForRegisterdUser { get; set; }
        public bool IsDefaultForStaffUser { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool RecordDeleted { get; set; }
    
        public virtual ICollection<OrganizationUnit> OrganizationUnit1 { get; set; }
        public virtual OrganizationUnit OrganizationUnit2 { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
