//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ActionList = new HashSet<ActionList>();
            this.ProjectClientDetail = new HashSet<ProjectClientDetail>();
            this.Resources = new HashSet<Resources>();
            this.TimeSheet = new HashSet<TimeSheet>();
            this.ProjectGroup = new HashSet<ProjectGroup>();
        }
    
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CommunicationEmailId { get; set; }
        public string CommunicationEmailPassword { get; set; }
        public string SourceControlDetail { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> RecordDeleted { get; set; }
        public Nullable<int> ProjectLead { get; set; }
        public string ProjectUrl { get; set; }
    
        public virtual ICollection<ActionList> ActionList { get; set; }
        public virtual ICollection<ProjectClientDetail> ProjectClientDetail { get; set; }
        public virtual ICollection<Resources> Resources { get; set; }
        public virtual ICollection<TimeSheet> TimeSheet { get; set; }
        public virtual ICollection<ProjectGroup> ProjectGroup { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
