//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectClientDetail
    {
        public int ProjectClientDetailId { get; set; }
        public int ProjectId { get; set; }
        public int ClientDetailId { get; set; }
        public bool IsMandatoryToIncludeInCommunication { get; set; }
    
        public virtual ClientDetail ClientDetail { get; set; }
        public virtual Project Project { get; set; }
    }
}
