//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrer
    {
        public Referrer()
        {
            this.Candidate = new HashSet<Candidate>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int ReferrerId { get; set; }
        public string ReferrerName { get; set; }
    
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
