//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.InterviewDetailSkill = new HashSet<InterviewDetailSkill>();
            this.EmployeeSkill = new HashSet<EmployeeSkill>();
        }
    
        public int SkillId { get; set; }
        public string SkillName { get; set; }
        public Nullable<int> TechnologyId { get; set; }
    
        public virtual ICollection<InterviewDetailSkill> InterviewDetailSkill { get; set; }
        public virtual Technology Technology { get; set; }
        public virtual ICollection<EmployeeSkill> EmployeeSkill { get; set; }
    }
}
