//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMPMGMT.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technology
    {
        public Technology()
        {
            this.Candidate = new HashSet<Candidate>();
            this.Skill = new HashSet<Skill>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int TechnologyId { get; set; }
        public string TechnologyName { get; set; }
    
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual ICollection<Skill> Skill { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
